config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users

  resources :users do
	  resources :custom_statements
  end
  
  get 'welcome/index'

  get 'welcome/login'

  get 'welcome/signup'

  get 'welcome/about'

  get 'welcome/features'

  get 'welcome/users'

  get 'welcome/profile'

  get 'welcome/inbox'

  get 'welcome/messages'

  get 'welcome/events'

  resources :messagings

  root to: 'welcome#index'
end

app/models/custom_statement.rb
class CustomStatement < ActiveRecord::Base
  belongs_to :user
end

app/controllers/custom_statements_controller.rb
class CustomStatementsController < ApplicationController
  def create
     @user = User.find(params[:user_id])

     if @user.custom_statements.create(custom_statement_params)
       redirect_to @user,
           notice: 'Custom Statement was successfully created.'
     else
        redirect_to @user,
           alert: 'Error creating Custom Statement.'
     end
  end # create method end.

# ADDED:

  # GET /posts/:post_id/comments
  # GET /posts/:post_id/comments.xml
  def index
    #1st you retrieve the post thanks to params[:post_id]
    user = User.find(params[:user_id])
    #2nd you get all the comments of this post
    @custom_statements = user.custom_statements

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @custom_statements }
    end
  end

  # GET /posts/:post_id/comments/:id
  # GET /comments/:id.xml
  def show
    #1st you retrieve the post thanks to params[:post_id]
    user = User.find(params[:user_id])
    #2nd you retrieve the comment thanks to params[:id]
    @custom_statement = user.custom_statements.find(params[:id])

    #puts "in custom statement show method."

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @custom_statement }
    end
  end

  # GET /posts/:post_id/comments/new
  # GET /posts/:post_id/comments/new.xml
  def new
    #1st you retrieve the post thanks to params[:post_id]
    user = User.find(params[:user_id])
    #2nd you build a new one
    @custom_statement = user.custom_statements.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @custom_statement }
    end
  end

  # GET /posts/:post_id/comments/:id/edit
  def edit
    #1st you retrieve the post thanks to params[:post_id]
    user = User.find(params[:user_id])
    #2nd you retrieve the comment thanks to params[:id]
    @custom_statement = user.custom_statements.find(params[:id])
  end

  # POST /posts/:post_id/comments
  # POST /posts/:post_id/comments.xml
#   def create
#     #1st you retrieve the post thanks to params[:post_id]
#     user = User.find(params[:user_id])
#     #2nd you create the comment with arguments in params[:comment]
#     @custom_statement = user.custom_statements.create(params[:custom_statement])

#     respond_to do |format|
#       if @custom_statement.save
#         #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
#         format.html { redirect_to([@custom_statement.user, @custom_statement], :notice => 'Custom Statement was successfully created.') }
#         #the key :location is associated to an array in order to build the correct route to the nested resource comment
#         format.xml  { render :xml => @custom_statement, :status => :created, :location => [@custom_statement.user, @custom_statement] }
#       else
#         format.html { render :action => "new" }
#         format.xml  { render :xml => @custom_statement.errors, :status => :unprocessable_entity }
#       end
#     end
#   end

  # PUT /posts/:post_id/comments/:id
  # PUT /posts/:post_id/comments/:id.xml
  def update
    #1st you retrieve the post thanks to params[:post_id]
    user = User.find(params[:user_id])
    #2nd you retrieve the comment thanks to params[:id]
    @custom_statement = user.custom_statements.find(params[:id])

    respond_to do |format|
      if @custom_statement.update(custom_statement_params)
        format.html { redirect_to [@custom_statement.user, @custom_statement], notice: 'Custom Statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_statement }
      else
        format.html { render :edit }
        format.json { render json: @custom_statement.errors, status: :unprocessable_entity }
      end
#       if @custom_statement.update_attributes(params[:custom_statement])
#         #1st argument of redirect_to is an array, in order to build the correct route to the nested resource comment
#         format.html { redirect_to([@custom_statement.user, @custom_statement], :notice => 'Custom Statment was successfully updated.') }
#         format.xml  { head :ok }
#       else
#         format.html { render :action => "edit" }
#         format.xml  { render :xml => @custom_statement.errors, :status => :unprocessable_entity }
#       end
    end
  end

  # DELETE /posts/:post_id/comments/1
  # DELETE /posts/:post_id/comments/1.xml
  def destroy
    #1st you retrieve the post thanks to params[:post_id]
    user = User.find(params[:user_id])
    #2nd you retrieve the comment thanks to params[:id]
    @custom_statement = user.custom_statements.find(params[:id])
    @custom_statement.destroy

    respond_to do |format|
      #1st argument reference the path /s/:user_id/custom_statements/
      format.html { redirect_to(user_custom_statements_url) }
      format.xml  { head :ok }
    end
  end
#end

# == added end.

private

  def custom_statement_params
    params.require(:custom_statement).permit(:statement, :importance, :degree_of_truth)
  end # comment_params end.

end

app/helpers/custom_statements_helper.rb
module CustomStatementsHelper
end

app/views/custom_statements/_custom_statements.html.erb
Custom Statement: <%= custom_statement.statement %>

<blockquote>
    Importance: <%= custom_statement.importance %> / 5
    Degree of truth: <%= custom_statement.degree_of_truth %> / 10
</blockquote>

app/views/custom_statements/_form.html.erb
<style>
  p.big
  {
    font-weight:bold;
    font-size:24px;
  }
  #main-container
  {
    margin:0 auto;
    width: 90%;
  }
  #whitebackground
  {
    background-color: white;
    box-shadow: 4px 4px 4px rbga(50,50,50, 0.75);
    width: 700px;
    margin-top:18px;
  }
</style>




<%= form_for [@custom_statement.user, @custom_statement] do |f| %>

    <% if @custom_statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom_statement.errors.count, "error") %> prohibited this custom statement from being saved:</h2>

      <ul>
      <% @custom_statement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
<div id = "main-container" align = "center">
<section id = "whitebackground">
    <div class='field'>
     <br><br> <p class="big">Statement:</p><br><br>
      <%= f.text_field :statement %>
    </div>

    <div class='field'>
      <br><br>
      <p class="big">Importance</p><br><br>
      <%= f.label :importance, "0 - Not important at all in a match", :value => 0 %>
      <%= f.radio_button :importance, 0 %>
      <%= f.label :importance, "1 - Rarely important in a match", :value => 1 %>
      <%= f.radio_button :importance, 1 %>
      <%= f.label :importance, "2 - Sometimes important in a match", :value => 2 %>
      <%= f.radio_button :importance, 2 %>
      <%= f.label :importance, "3 - Normally important in a match", :value => 3 %>
      <%= f.radio_button :importance, 3 %>
      <%= f.label :importance, "4 - Almost always important in a match", :value => 4 %>
      <%= f.radio_button :importance, 4 %>
      <%= f.label :importance, "5 - Incredibly important in a match", :value => 5 %>
      <%= f.radio_button :importance, 5 %>
    </div>

    <div class='field'>
      <br><br><p class="big">Degree of Truth:</p><br><br>
      <%= f.label :degree_of_truth, "0 - Not true at all for me", :value => 0 %>
      <%= f.radio_button :degree_of_truth, 0 %>
      <%= f.label :degree_of_truth, "1 - Rarely true for me", :value => 1 %>
      <%= f.radio_button :degree_of_truth, 1 %>
      <%= f.label :degree_of_truth, "2 - Sometimes true for me", :value => 2 %>
      <%= f.radio_button :degree_of_truth, 2 %>
      <%= f.label :degree_of_truth, "3 - Normally true for me", :value => 3 %>
      <%= f.radio_button :degree_of_truth, 3 %>
      <%= f.label :degree_of_truth, "4 - Almost always true for me", :value => 4 %>
      <%= f.radio_button :degree_of_truth, 4 %>
      <%= f.label :degree_of_truth, "5 - Incredibly true for me", :value => 5 %>
      <%= f.radio_button :degree_of_truth, 5 %>
      <br><br><br>
    </div>

  </section>
</div>
<br><br>
<div id = "main-container" align = "center">

    <div class='actions'>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/custom_statements/edit.html.erb
<h1>Editing Custom Statement</h1>

<%= render 'form' %>

<!-- /posts/:post_id/comments/:id -->
<%= link_to 'Show', [@custom_statement.user, @custom_statement] %> |
<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', user_custom_statements_path(@custom_statement.user) %>

app/views/custom_statements/index.html.erb
<style>
  p.red
  {
    color:red;
    font-size:16px;
  }
  #main-container
  {
    margin:0 auto;
    width: 90%;
  }
  #whitebackground
  {
    background-color: white;
    box-shadow: 4px 4px 4px rbga(50,50,50, 0.75);
    width: 700px;
    margin-top:18px;
  }
</style>
<h1>Your Custom Requirements</h1>
<div id = "main-container" align = "center">
<section id = "whitebackground">
<table width = "65%" cellspacing = "5" cellpadding = "10">

  <tr>
    <th><p class = "red" align = "center"> Requirement </p></th>
    <th><p class = "red" align = "center"> Importance  </p></th>
    <th><p class = "red" align = "center"> Degree of Truth </p></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @custom_statements.each do |custom_statement| %>
  <tr>
    <td><p align = "center"><%= custom_statement.statement %></p></td>
    <td><p align = "center"><%= custom_statement.importance %> / 5</p></td>
    <td><p align = "center"><%= custom_statement.degree_of_truth %> / 5</p></td>

    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to 'Show', [custom_statement.user, custom_statement] %>   </td>
    <!-- /posts/:post_id/comments/:id/edit -->
    <td><%= link_to 'Edit', edit_user_custom_statement_path(custom_statement.user, custom_statement)%>   </td>
    <!-- /posts/:post_id/comments/:id -->
    <td><%= link_to 'Destroy', [custom_statement.user, custom_statement], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

</table>
  </section>
</div>


<br />

<%= link_to "Back", :back %>|
<%= link_to 'New Custom Statement', new_user_custom_statement_path %>

app/views/custom_statements/new.html.erb
<h1>New Custom Statement</h1>

<%= render 'form' %>

<%= link_to 'Back', user_custom_statements_path%>

app/views/custom_statements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Statement:</b>
  <%= @custom_statement.statement %>
</p>

<p>
  <b>Importance:</b>
  <%= @custom_statement.importance %>
</p>

<p>
  <b>Degree of Truth:</b>
  <%= @custom_statement.degree_of_truth %>
</p>

<!-- /posts/:post_id/comments/:id/edit -->
<%= link_to 'Edit', edit_user_custom_statement_path(@custom_statement.user, @custom_statement) %> |
<!-- /posts/:post_id/comments/ -->
<%= link_to 'Back', user_custom_statements_path(@custom_statement.user) %>