config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users

  resources :users do
	  resources :custom_statements
  end
  
  get 'welcome/index'

  get 'welcome/login'

  get 'welcome/signup'

  get 'welcome/about'

  get 'welcome/features'

  get 'welcome/users'

  get 'welcome/profile'

  get 'welcome/inbox'

  get 'welcome/messages'

  get 'welcome/events'

  resources :messagings

  root to: 'welcome#index'
end

app/models/messaging.rb
class Messaging < ActiveRecord::Base
    attr_accessor :image_cache
  has_attached_file :image, styles: { medium: "300x300>", large: "600x600>" }, default_url: "/images/:style/missing.png",
                    :url => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

 validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def cache_images
    if image.staged?
      if invalid?
        FileUtils.cp(image.queued_for_write[:original].path, image.path(:original))
        @image_cache = encrypt(image.path(:original))
      end
    else
      if @image_cache.present?
        File.open(decrypt(@image_cache)) {|f| assign_attributes(image: f)}
      end
    end
  end

  private

  def decrypt(data)
    return '' unless data.present?
    cipher = build_cipher(:decrypt, 'mypassword')
    cipher.update(Base64.urlsafe_decode64(data).unpack('m')[0]) + cipher.final
  end

  def encrypt(data)
    return '' unless data.present?
    cipher = build_cipher(:encrypt, 'mypassword')
    Base64.urlsafe_encode64([cipher.update(data) + cipher.final].pack('m'))
  end

  def build_cipher(type, password)
    cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').send(type)
    cipher.pkcs5_keyivgen(password)
    cipher
  end


end

app/controllers/messagings_controller.rb
class MessagingsController < ApplicationController
  before_action :set_messaging, only: [:show, :edit, :update, :destroy]

  # GET /messagings
  # GET /messagings.json
  def index
    @search = MessagingSearch.new(params[:search])
    @messagings = @search.scope
  end

  # GET /messagings/1
  # GET /messagings/1.json
  def show
  end

  # GET /messagings/new
  def new
    @messaging = Messaging.new
  end

  # GET /messagings/1/edit
  def edit
  end

  # POST /messagings
  # POST /messagings.json
  def create
  @messaging = Messaging.new(messaging_params)
  @messaging.cache_images

    respond_to do |format|
      if @messaging.save
        format.html { redirect_to @messaging, notice: 'Messaging was successfully created.' }
        format.json { render :show, status: :created, location: @messaging }
      else
        format.html { render :new }
        format.json { render json: @messaging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messagings/1
  # PATCH/PUT /messagings/1.json
  def update

    respond_to do |format|
      if @messaging.update(messaging_params)
        format.html { redirect_to @messaging, notice: 'Messaging was successfully updated.' }
        format.json { render :show, status: :ok, location: @messaging }
      else
        format.html { render :edit }
        format.json { render json: @messaging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messagings/1
  # DELETE /messagings/1.json
  def destroy
    @messaging.destroy
    respond_to do |format|
      format.html { redirect_to messagings_url, notice: 'Messaging was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_messaging
      @messaging = Messaging.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def messaging_params
      params.require(:messaging).permit(:date, :receiver, :sender, :message, :image)
    end
end

app/helpers/messagings_helper.rb
module MessagingsHelper
end

app/views/messagings/_form.html.erb
<%= form_for @messaging, html: {multipart: true} do |f| %>
  <% if @messaging.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@messaging.errors.count, "error") %> prohibited this messaging from being saved:</h2>

      <ul>
      <% @messaging.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :receiver %><br>
    <%= f.text_field :receiver %>
  </div>
  <div class="field">
    <%= f.label :sender %><br>
    <%= f.text_field :sender %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messagings/edit.html.erb
<h1>Editing Messaging</h1>

<%= render 'form' %>

<%= link_to 'Show', @messaging %> |
<%= link_to 'Back', messagings_path %>

app/views/messagings/index.html.erb
<style>
  #main-container
  {
    margin:0 auto;
    width: 90%;
  }
  #whitebackground
  {
    background-color: white;
    box-shadow: 4px 4px 4px rbga(50,50,50, 0.75);
    width: 700px;
    margin-top:18px;
  }
</style>
<div class="row">
<p id="notice"><%= notice %></p>
  <h1>Public Messages</h1>
  <div class="pull-right range-query">
    <%= form_tag messagings_path, method: :get do %>
      <%= text_field_tag 'search[date_from]',@search.date_from %>

      <%= text_field_tag 'search[date_to]', @search.date_to%>
      <%= submit_tag 'Search', class: 'btn search-button' %>
     <% end %>
  </div>
 </div>
<div id = "main-container">
  <section id = "whitebackground">
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Receiver</th>
          <th>Sender</th>
          <th>Message</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @messagings.each do |messaging| %>
          <tr>
            <td><%= messaging.date.strftime("%Y/%m/%d") %></td>
            <td><%= messaging.sender %></td>
            <td><%= image_tag messaging.image.url(:medium) %></td>
            <td><%= messaging.message %></td>
            <td><%= link_to 'Show', messaging, class: 'btn-mini btn' %></td>
            <td><%= link_to 'Edit', edit_messaging_path(messaging), class: 'btn-mini btn-success' %></td>
            <td><%= link_to 'Destroy', messaging, method: :delete, class: 'btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
  </section>
</div>
<br>
<br>
<h1><%= link_to 'New Message', new_messaging_path %></h1>
<br><br>

app/views/messagings/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messagings_path %>

app/views/messagings/show.html.erb
<p id="notice"><%= notice %></p>
<% image_tag @messaging.image.url(:medium) %>
<p>
  <strong>Date:</strong>
  <%= @messaging.date %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @messaging.receiver %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @messaging.sender %>
</p>

<p>
  <strong>Message:</strong>
  <%= @messaging.message %>
</p>

<%= link_to 'Edit', edit_messaging_path(@messaging) %> |
<%= link_to 'Back', messagings_path %>