config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users

  resources :users do
	  resources :custom_statements
  end
  
  get 'welcome/index'

  get 'welcome/login'

  get 'welcome/signup'

  get 'welcome/about'

  get 'welcome/features'

  get 'welcome/users'

  get 'welcome/profile'

  get 'welcome/inbox'

  get 'welcome/messages'

  get 'welcome/events'

  resources :messagings

  root to: 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
    attr_accessor :image_cache
  has_attached_file :image, styles: { medium: "300x300>", large: "600x600>" }, default_url: "/images/:style/missing.png",
                    :url => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

 validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def cache_images
    if image.staged?
      if invalid?
        FileUtils.cp(image.queued_for_write[:original].path, image.path(:original))
        @image_cache = encrypt(image.path(:original))
      end
    else
      if @image_cache.present?
        File.open(decrypt(@image_cache)) {|f| assign_attributes(image: f)}
      end
    end
  end

  private

  def decrypt(data)
    return '' unless data.present?
    cipher = build_cipher(:decrypt, 'mypassword')
    cipher.update(Base64.urlsafe_decode64(data).unpack('m')[0]) + cipher.final
  end

  def encrypt(data)
    return '' unless data.present?
    cipher = build_cipher(:encrypt, 'mypassword')
    Base64.urlsafe_encode64([cipher.update(data) + cipher.final].pack('m'))
  end

  def build_cipher(type, password)
    cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').send(type)
    cipher.pkcs5_keyivgen(password)
    cipher
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :location, :details, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {multipart: true} do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<style>
   #main-container
  {
    margin:0 auto;
    width: 90%;
  }
  #whitebackground
  {
    background-color: white;
    box-shadow: 4px 4px 4px rbga(50,50,50, 0.75);
    width: 700px;
    margin-top:18px;
  }
</style>
<p id="notice"><%= notice %></p>

<h1>Events</h1>
<div id = "main-container">
  <section id = "whitebackground">
<div class="media">
     <div class="media-body">

<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.location %></td>
        <td><%= event.details %></td>
        <td><%= image_tag event.image.url(:medium) %></td>
        <td><%= link_to 'Show', event, class: 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_event_path(event), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', event, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>
  </div>
</div>
    </section>
</div>

<br>
<br>
<h1><%= link_to 'New Event', new_event_path %></h1>
<br><br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<% image_tag @event.image.url(:medium) %>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Details:</strong>
  <%= @event.details %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>