config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users

  resources :users do
	  resources :custom_statements
  end
  
  get 'welcome/index'

  get 'welcome/login'

  get 'welcome/signup'

  get 'welcome/about'

  get 'welcome/features'

  get 'welcome/users'

  get 'welcome/profile'

  get 'welcome/inbox'

  get 'welcome/messages'

  get 'welcome/events'

  resources :messagings

  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bumpinuglies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <ul class="nav nav-tabs">
    <% if current_user %>
              <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb), unless: current_user.avatar.nil?) %></li>
     <% end %>
      <li><%= link_to "Home",root_path %></li>
      <% if current_user %>
        <li><%= link_to "Sign Out",destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up",new_user_registration_path %></li>
        <li><%= link_to "Log In",new_user_session_path %></li>
      <% end %>


     <li><%= link_to "About Us",welcome_about_path %></li>
     <li><%= link_to "Features",welcome_features_path %></li>






      <% if current_user %>
        <li><%= link_to "Edit Profile",edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Profile",new_user_session_path %></li>
      <% end %>



     <li><%= link_to "Messages",messagings_path %></li>
     <li><%= link_to "Events",events_path %></li>
            <li><%= link_to "Find your match!", welcome_inbox_path %>

    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
       </div>
    <% elsif flash[:error] %>
       <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
       </div>
    <% elsif flash[:alert] %>
       <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
       </div>
    <% end %>


<%= yield %>
  </div>
</body>
</html>